export const MODELS_URL = process.env.MODELS_URL ?? "https://mdb.yor.ovh/v1/files"

export const MODELS = [
  "1_DWTP_ds_span_p",
  "1x-fast-jpeg-illust-v1",
  "1x_Bendel_Halftone",

  "1x-MangaJPEGHQ",
  "1x-MangaJPEGHQPlus",
  "1x-MangaJPEGLQ",
  "1x_MangaJPEGMQ",

  "1x_Saiyajin_DeJPEG_300000_G",
  "1x_eula_digimanga_bw_v3_nc1_52k",
  "2x_WTP_MCover_cugan",
  "2x_umzi_Mahou_cugan",
  "4DWTP_mangasoup_cugan_p",
  "4x-AnimeSharp",
  "4x-UltraMix_Balanced",
  "4x-UltraMix_Restore",
  "4x-UltraMix_Smooth",
  "4xRealWebPhoto_v3_atd",
  "4x_DWTP_DS_ATDl",
  "4x_DWTP_DS_ATDl2",
  "4x_DWTP_DS_DAT2_V3",
  "4x_DWTP_DS_dat2_v3_2",
  "4x_DWTP_dehesragan_V4",
  "4x_DWTP_descreenon_dat2",

  "4x_MangaJaNai_1200p_V1RC71_ESRGAN_70k",
  "4x_MangaJaNai_1300p_V1RC1_ESRGAN_75k",
  "4x_MangaJaNai_1400p_V1RC3_ESRGAN_105k",
  "4x_MangaJaNai_1500p_V1RC1_ESRGAN_105k",
  "4x_MangaJaNai_1600p_V1RC1_ESRGAN_70k",
  "4x_MangaJaNai_1920p_V1RC1_ESRGAN_105k",
  "4x_MangaJaNai_2048p_V1RC1_ESRGAN_70k",
  "4x_MangaJaNai_V1RC34_ESRGAN_760k",

  "4x_dwtp_ds_atdl3",
  "4x_dwtp_ds_rgts_v1",
  "4x_eula_digimanga_MiA_65k",
  "4x_eula_digimanga_bw_v2_nc1_307k",
  "4x_span_franken",
  "4x_umzi_dehalfton_realplksr_v1",
  "4x_umzi_digital_art_rplksr_v1",
  "4x_umzi_digital_art_span_v1",
  "4x_umzi_digital_art_mosr",
  "4x_wtp_ms_atdl_v1",
  "4x_wtp_ms_beta_atdl",
  "4x_wtp_ms_plksr_v1",
  "4x_wtp_ms_rplksr_beta",
  "4x_dwtp_ds_rplksr_delta",
  "4x_umzi_digital_art_rplksr_v2",
  "4x_MangaScale_v1_mosr",
  "4x_umzi_decompress_mosr",
]
